version: 2
jobs:
    build:
        docker:
          - image: dronecourseepfl/dronecourse:spring_2018
        steps:
            - checkout
            - run:
                name: Compile
                command: |
                  make _dronecourse
            - run:
                name: Test
                command: |
                  make _dronecourse test_all:
            - run:
                name: Evaluate
                command: |
                   export HEADLESS=true
                   Xvfb :99 -shmem -screen 0 1280x1024x24 > /dev/null 2>&1 &
                   make clean
                   export NO_NINJA_BUILD=1
                   export DISPLAY=':99.0'
                   ./tp_eval/batch_evaluate.sh 1 0 0
            - store_artifacts:
                path: build_posix_sitl_dronecourse/tmp/rootfs/fs/microsd/log